### ISSUE TITLE
Pick CameraRoll by default

### ISSUE THREAD

**Issue by ahbou** [donobono/DoImagePickerController#1]
Hello there
Is there a way to pick the camera roll by default and keep the album selection?
Thanks.

**Comment by donobono** [comment]
Current default album is camera roll. Doesn't work for you?
The second issue which you mentioned, I'll add it ASAP.

Thank you for your feedback!!

**Comment by ahbou** [comment]
On device it picks a shared photo stream album as the first one.
Thank you.

**Comment by donobono** [comment]
Ah.. I didn't test with photo stream.. I'll check it.. Thanks!!!

**Comment by donobono** [comment]
I pull fixed source.. Please check it.. 
Thanks!! :)

**Comment by ahbou** [comment]
Thank you!
Works like a charm.
