### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by former1976** [donobono/DoImagePickerController#2]
I love your project, and i will love to use the in a mini game I work with.

In the game, the user can choose the own pictures, and use them in the game.

My questions is, how can i load the picture in to the, the user have choose. 

my code look like this
- (void) loadCellImages {
  [self unloadCellImages];
  for (int i=1;i<(totalcolors+1);i++) {
  [cellImages addObject:[UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:[NSString stringWithFormat:@"%@%d",[self getFilePrefix],i] ofType:@"png"]]];
  }
  }

thanks Jens

**Comment by donobono** [comment]
Try like this :

DoActionSheet *vActionSheet = [[DoActionSheet alloc] init];
vActionSheet.nAnimationType = DoTransitionStyleNormal;
vActionSheet.nContentMode = DoContentImage;
vActionSheet.iImage = [UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:[NSString stringWithFormat:@"%@%d",[self getFilePrefix],i] ofType:@"png"]];
...

Do you want this? If not, ask me again.. :-)

**Comment by donobono** [comment]
Ooooooops... Sorry.. My answer was wrong..

DoImagePickerController can get photos only from album of device, can not get from bundle now.. You should make by yourself with scrollview or other controls.. 

Thank you..

**Comment by former1976** [comment]
okay thanks I will do that. good  work.
