### ISSUE TITLE
Not Work in iPad

### ISSUE THREAD

**Issue by heefan** [donobono/DoImagePickerController#5]
Hi,

This is great project, however, I found it cannot work in iPad.
It seems it has memory leak. 

I tested in iOS7.1 Xcode5.1 with MacOSX 10.9

The memory leak seems from the 3rdSource (UIImage-ResizeMagic).

When I try to present your DoImagePickerController from super view, it cannot display photos, and then crash as memory exhaust.

Regards，

**Comment by heefan** [comment]
Hi, 
Sorry for the bug report. The problem is caused by missing `nColumnCount` in my view controller.
Cheers,

**Comment by donobono** [comment]
Good!
When you finish and release your app, let me know.. :-)

**Comment by heefan** [comment]
Sure. One more thing, I specified `nColumnCount=4`, however, it display  12 pictures for each row.
I haven't read the code, so I just report it to you. 
I will look into later. 
Thanks

**Comment by donobono** [comment]
Actually, becasue this contoller is made for only iPhone screen size, there are some problem on iPad like your situation. If you want to change photo count for each row, your should fix this code of DoImagePickerController.m as you want.
- (CGSize)collectionView:(UICollectionView _)collectionView layout:(UICollectionViewLayout_)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath
  {
  // fix here!!
  if (_nColumnCount == 2)
      return CGSizeMake(158, 158);
  else if (_nColumnCount == 3)
      return CGSizeMake(104, 104);
  else if (_nColumnCount == 4)
      return CGSizeMake(77, 77);
  
  return CGSizeZero;
  }

**Comment by heefan** [comment]
Thanks for pointing out. It would be great to support both iPhone and iPad.
I will do it in my App first
Cheers
